:openapi: https://www.openapis.org/
:converter-jackson: https://github.com/openapi-processor/openapi-parser/tree/master/openapi-parser-jackson
:converter-snakeyaml: https://github.com/openapi-processor/openapi-parser/tree/master/openapi-parser-snakeyaml

**work in progress**

It is usable, but has the following limitations at the moment:

* it does support most but not all OpenAPI object properties
* JSON schema validation is only available for OpenAPI 3.0.x

source code gifts (i.e pull requests) are welcome :-)

== openapi-parser & validator

a Java 8 based link:{openapi}[OpenAPI] 3.0.x & 3.1 parser with validation and pluggable document reader & json/yaml converter.

* parse OpenAPI 3.0.x & 3.1
* validate OpenAPI 3.0.x & 3.1 (json schema validation, handles $ref's in the OpenAPI document)
* separate apis for OpenAPI 3.0 & 3.1
* easily get resolved $ref object
* minimal dependencies
* pluggable document reader
* pluggable json/yaml converter
* pluggable `format` validators (planned)

=== user-friendly api

the parser tries to provide a *user-friendly* api in the sense that it

* minimizes *null* values where possible
* throws if *required* properties are not set
* it is *read only*
* it resolves `$ref` objects, i.e. $ref objects have a `getRefObject()`
* it is very close to the specification (OpenAPI 3.0 & 3.1)

Drawback is, that with the current api it is not possible (for some properties) to detect if a property is set in the OpenAPI description or if it is not given.

=== raw api

It is easy to create an alternative *raw* api that is based on the *structure* of the OpenAPI description that provides the *raw* values of the properties.

I'm not sure yet if I want to mix *raw* and *user-friendly* in a single api. *Do we need both styles at the same time?*

==== implementation

for example, the *usr-friendly* `model.v30.OpenApi` (`model.v31.OpenApi`) model object has a method

    Info getInfo ();

to create a *raw* api

it is possible to extend the existing api with

    Info getInfoRaw ();

or to change the existing api to use `Optional`

    Optional<Info> getInfo ();

or to create a new api `model.v30r.OpenApi` with a `@Nullable` signature

    @Nullable Info getInfo ();


=== minimizing null values

Minimizing null values means that

- for a missing/optional array properties it will return an empty collection
- for other missing/optional properties it will return the default value if any is specified by the OpenAPI specification

For example the `required` property of a `parameter` has a `false` default value and the api will return false in case `required` is not explicitly set in the OpenAPI description.

=== yaml/json converter

the *parser* is internally using `Map<String, Object>` to represent the OpenAPI object tree to be independent of a specific yaml/json parser. It will work with any yaml/json parser that is able to convert an OpenAPI yaml or json to a `Map<String, Object>` object tree.

link:{converter-jackson}[`openapi-parser-jackson`] provides a default implementation that is based on jackson.

== usage

code example for parsing an OpenAPI yaml file and running the JSON Schema validation.

[source,java]
----
import io.openapiparser.jackson.JacksonConverter;
import io.openapiparser.model.v30.OpenApi;
import io.openapiparser.reader.UriReader;
import io.openapiparser.schema.*;
import io.openapiparser.snakeyaml.SnakeYamlConverter;
import io.openapiparser.validator.Validator;
import io.openapiparser.validator.ValidatorSettings;
import io.openapiparser.validator.result.*;

public class Example {

    void parseAndValidate () {
        // setup resolver (handles documents and $refs)
        Reader reader = new UriReader ();
        DocumentStore documents = new DocumentStore ();
        Converter converter = new SnakeYamlConverter ();
        // Converter converter = new JacksonConverter ();
        Resolver resolver = new Resolver (reader, converter, documents);

        // parser OpenAPI file or url
        OpenApiParser parser = new OpenApiParser (resolver);
        OpenApiResult result = parser.parse ("openapi.yaml");
        // OpenAPI 3.1.x with model.v31.OpenAPI import
        OpenApi model = result.getModel (OpenApi.class);

        // validate OpenAPI
        SchemaStore store = new SchemaStore (resolver);
        ValidatorSettings settings = new ValidatorSettings ();
        Validator validator = new Validator (settings);
        boolean valid = result.validate (validator, store);

        // print validation messages (i.e. errors)
        MessageCollector collector = new MessageCollector (result.getValidationMessages ());
        LinkedList<Message> messages = collector.collect ();
        MessageTextBuilder builder = new MessageTextBuilder ();
        for (Message message : messages) {
            System.out.println (builder.getText(message));
        }
    }
}
----
