:json-schema-testsuite: https://github.com/json-schema-org/JSON-Schema-Test-Suite

== json-schema-validator

this is a dependency-less java 8 based JSON Schema validator with pluggable json parser.

Used by openapi-parser but also usable as standalone JSON Schema validator.

== features

* supports drafts *2020-12*, *2019-09*, *7*, *6* and *4*
* supports *annotations*
* supports the output format: *flag*, *basic* & *verbose*.
* passes all required tests of the official link:{json-schema-testsuite}[JSON Schema Test Suite] & most *optional* tests

== limitations

Vocabularies support is currently limited. Enabling/disabling vocabularies is not yet fully implemented except for *format-assertion*, *format-validation*.

It implements the `format` s as listed. See the limitations below.

* *2020-12* (https://json-schema.org/draft/2020-12/schema)

* *2019-09* (https://json-schema.org/draft/2019-09/schema)
** format: *duration* (not implemented)
** format: *uuid* (`jav.util.UUID`)

* *draft-07* (https://json-schema.org/draft-07/schema#)
** `contentMediaType`: not validated
** `contentEncoding`: not validated
** format: *date* (`java.time.LocalDate`)
** format: *time* (`java.time.OffsetTime`, see limitations)
** format: *idn-email* (not implemented)
** format: *idn-hostname* (not implemented)
** format: *iri* (not implemented)
** format: *iri-reference* (not implemented)
** format: *regex* (`java.util.regex.Pattern`, see limitations)
** format: *relative-json-pointer.json* (not implemented)
** format: *uri-template.json* (not implemented)
** format: see Draft 6 formats

* *draft-06* (https://json-schema.org/draft-06/schema#)
** format: *uri-reference* (code)
** format: *json-pointer* (not implemented)
** format: *uri-template* (not implemented)
** format: see Draft 4 formats

* *draft-04* (http://json-schema.org/draft-04/schema#) => OpenAPI 3.0.x
** format: *date-time* (`java.time.OffsetDateTime`, see limitations)
** format: *email* (code)
** format: *hostname* (code)
** format: *ipv4* (code)
** format: *ipv6* (code)
** format: *uri* (code)

=== limitations

`io.openapiprocessor.json-schema-validator` uses jdk classes for `uri` handling & validating `format` s like, `time`, `date-time`, `uri` & `regex` assertions where possible.

Unfortunately the jdk classes do not conform to 100% to their corresponding standards which causes a few limitations and a number of test failures in the optional section of the json-validator test suite:

==== general: URI

`java.net.URI` does not fully support `urn:` uris. With a bit of custom code the validator supports `urn` s to pass all tests that use `urn` s.

==== general/format: ECMAScript regular expressions

* `[draft2020-12|draft2019-09|draft7|draft6|draft4]/optional/ecmascript-regex.json`

`java.util.regex` is not fully compatible with the ECMA 262 (i.e. JavaScript) regular expression dialect.

==== format: time

* `[draft2020-12|draft2019-09|draft7|draft6|draft4]/optional/format/time.json`

`java.time.format.DateTimeFormatter` doesn't support leap seconds. This causes the leap second specific tests to fail.

==== format: date-time

* `[draft2020-12|draft2019-09|draft7|draft6|draft4]/optional/format/date-time.json`

`java.time.format.DateTimeFormatter` doesn't support leap seconds. This causes the leap second specific tests to fail.
