name: release

on:
  release:
    types: [published]

jobs:

  publish:
    name: publish release

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
            11
            17

      - name: set up gradle
        uses: gradle/gradle-build-action@v2.9.0

      - name: publish release
        env:
          PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
          PUBLISH_KEY: ${{ secrets.PUBLISH_KEY }}
          SIGN_KEY: ${{ secrets.SIGN_KEY }}
          SIGN_PWD: ${{ secrets.SIGN_PWD }}
        run: |
          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
